spring:
  datasource:
    url: jdbc:h2:mem:assinatura
    driverClassName: org.h2.Driver
    username: tdsoft
    password: tdsoft
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: swagger-ui.html